language:
    - cpp

compiler:
    - clang
    - gcc

addons:
    apt:
        packages:
            - clang-3.7
            - libboost-dev

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
            
os:
    - linux

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
