sudo: false

language: generic

cache:
  apt: true

addons:
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - gcc-5
            - g++-5
            - libboost1.55-all-dev
          sources:
           - boost-latest
           - ubuntu-toolchain-r-test

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
