language: cpp
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-4.8-dev
    - g++-5
    - libboost1.62-dev
matrix:
  include:
    - os: linux
      compiler: clang
      env: CXXFLAGS="-pedantic -Werror"
    - os: linux
      compiler: gcc-5

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
