language: generic
os: osx
matrix:
  include:
    - os: linux
      env: GCC_VERSION=5 LIBCXX=Off
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - libboost-dev
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8 LIBCXX=On
      addons:
        apt:
          packages:
            - clang-3.8
            - libboost-dev
          sources: *sources

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
