sudo: false

language: c++

#cache:
#  apt: true

addons:
matrix:
  include:
    # Xcode 8
    - os: osx
      osx_image: xcode8
      #env: UNIT_TESTS=true BOOST_VERSION=default

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest --output-on-failure
