language: generic
os: osx
matrix:
  include:
    - os: linux
      env: GCC_VERSION=6 LIBCXX=Off
      addons: &gcc6
        apt:
          packages:
            - g++-6
            - libboost-dev
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.9 CC=clang-3.9 LIBCXX=On
      addons:
        apt:
          packages:
            - clang-3.9
            - libboost-dev
          sources: *sources

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
