sudo: false

language: generic

cache:
  apt: true

addons:
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
            - libboost1.55-all-dev
          sources:
            - boost-latest
            - ubuntu-toolchain-r-test

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
