language: cpp
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.8
    - g++-5
    - libboost1.58-dev
matrix:
  include:
    - os: linux
      compiler: clang-3.8
      env: CXXFLAGS="-pedantic -Werror"
    - os: linux
      compiler: gcc-5

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
