language: cpp

matrix:
    - env: CLANG_VERSION=4.0 BUILD_TYPE=Debug CPP=14 ASAN=On LIBCXX=On
      os: linux
      addons: &clang40
        apt:
          packages:
            - util-linux
            - clang-4.0
            - valgrind
            - libboost1.58-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - libboost1.58-dev

    # Test gcc-6: C++11/14/1z, Build=Debug/Release, ASAN=Off
    - env: GCC_VERSION=6 BUILD_TYPE=Debug CPP=14 ASAN=Off LIBCXX=Off
      os: linux
      addons: &gcc6
        apt:
          packages:
            - g++-6
            - valgrind
            - libboost1.58-dev
          sources:
            - ubuntu-toolchain-r-test            
            
script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
