language:
    - cpp

compiler:
    - clang
    - gcc

install:
    - sudo apt-get install libboost-dev

os:
    - linux

script:
    - mkdir _builds
    - cd _builds
    - cmake ..
    - make
    - ctest
