platform:
  - x64

configuration:
  - Debug

environment:
  BOOST_ROOT: C:\Libraries\boost
  BOOST_INCLUDEDIR: C:\Libraries\boost
  BOOST_LIBRARYDIR: C:\Libraries\boost\lib64-msvc-14.0

os:
  - Visual Studio 2015

install:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  - mkdir build && cd build
  - cmake ..

build:
  project: C:/projects/liquidpp/build/ALL_BUILD.vcxproj

test_script:
  - ctest
  
