platform:
  - x86
  #- x64

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_62_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_62_0\lib32-msvc-14.0

configuration:
  - Debug

#environment:
#  BOOST_ROOT: C:\Libraries\boost_1_59_0
#  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

os:
  - Visual Studio 2015

install:
  #- ps: nuget install boost -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.62.0
  #- ps: nuget install boost_locale-vc140 -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.62.0
  - ps: nuget install rapidjson -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.0.2
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  - mkdir build && cd build
  - cmake -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ..

build:
  project: C:/projects/liquidpp/build/ALL_BUILD.vcxproj

test_script:
  - ctest --build-config %configuration% --output-on-failure --test-output-size-passed 2048
