platform:
  - x86
  - x64

configuration:
  - Debug

#environment:
#  BOOST_ROOT: C:\Libraries\boost_1_59_0
#  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0

os:
  - Visual Studio 2015

install:
  - ps: nuget install boost -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.62.0
  - ps: nuget install rapidjson -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.0.2
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  - mkdir build && cd build
  - cmake -DBOOST_INCLUDEDIR:PATH="C:\projects\liquidpp\boost.1.62.0.0\lib\native\include" -DBOOST_LIBRARYDIR:PATH="C:\projects\liquidpp\boost_libs" ..

build:
  project: C:/projects/liquidpp/build/ALL_BUILD.vcxproj

test_script:
  - ctest --build-config %configuration% --output-on-failure --test-output-size-passed 2048
