platform:
  - x86
  - x64

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  BOOST_ROOT: C:\Libraries\boost_1_62_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_62_0\lib32-msvc-14.0

configuration:
  - Debug

os:
  - Visual Studio 2015

install:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  #- ps: nuget install rapidjson -o "${env:APPVEYOR_BUILD_FOLDER}" -Version 1.0.2
  - mkdir build && cd build
  - cmake -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ..

build:
  project: C:/projects/liquidpp/build/ALL_BUILD.vcxproj

test_script:
  #- C:\projects\liquidpp\build\test\Debug\liquidppTest.exe
  - ctest --build-config %configuration% --output-on-failure --test-output-size-passed 2048
