platform:
  - x64
configuration:
  - Debug

os:
  - Visual Studio 2015

build:
  parallel: true
  verbosity: normal

install:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  
build_script:
  - mkdir build && cd build
  - cmake ..
